### PR TITLE
added the following directories/folders to frontend

### PR DESCRIPTION
**Pull request by winniecwng**
UI, reducers, store, util, actions, and components directories

### CODE REVIEW

**Comment by amberhunt955** [comment]
I only see the the store directory, which has the store.js file. Did you add anything else to the folder structure? I don't think git can push empty directories.

**Comment by winniecwng** [comment]
> I only see the the store directory, which has the store.js file. Did you add anything else to the folder structure? I don't think git can push empty directories.

okay, got it. I'll add psuedo files into the directories then.

**Review by alexh205 — COMMENTED** [review]
The updates look good to me, so I do not have any further comments.

**Comment by amberhunt955** [comment]
Looks good to me too!

**Review by amberhunt955 — APPROVED** [review]

**Pull request merged**
